<?php

namespace Database\Seeders;

use App\Models\create_clothes_table;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClotheSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $productos = [

            // Camisetas
            [
                'nombre' => 'Camiseta',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Amarillo',
                'precio' => 5,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/camisetas/hombre_informal_camiseta_amarillo_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/94-hombreformalcamisetaamarillo.html',
            ],
            [
                'nombre' => 'Camiseta',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Beige',
                'precio' => 8,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/camisetas/hombre_informal_camiseta_beige_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/93-hombreformalcamisetabeige.html',
            ],
            [
                'nombre' => 'Camiseta',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Blanco',
                'precio' => 5,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/camisetas/hombre_informal_camiseta_blanco_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/92-hombreinformalcamisetablanco.html',
            ],
            [
                'nombre' => 'Camiseta',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Negro',
                'precio' => 7,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/camisetas/hombre_informal_camiseta_negro_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/91-hombreinformalcamisetanegro.html',
            ],
            [
                'nombre' => 'Camiseta',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Rojo',
                'precio' => 4,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/camisetas/hombre_informal_camiseta_rojo_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/90-hombreinformalcamisetarojo.html',
            ],
            [
                'nombre' => 'Camiseta',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Rosa',
                'precio' => 4,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/camisetas/hombre_informal_camiseta_rosa_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/89-hombreinformalcamisetarosa.html',
            ],
            [
                'nombre' => 'Camiseta',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Verde',
                'precio' => 6,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/camisetas/hombre_informal_camiseta_verde_001.png',
                'url' => 'https://daw05.medacarena.com.es/busqueda?controller=search&s=hombre_informal_camiseta_verde_001',
            ],
            [
                'nombre' => 'Camiseta',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Gris',
                'precio' => 7,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/camisetas/hombre_informal_camiseta_gris_001.png',
                'url' => 'https://daw05.medacarena.com.es/busqueda?controller=search&s=hombre_informal_camiseta_gris_001',
            ],
            [
                'nombre' => 'Camiseta',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Naranja',
                'precio' => 6,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/camisetas/hombre_informal_camiseta_naranja_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/99-hombreinformalcamisetanaranja001.html',
            ],
            [
                'nombre' => 'Camiseta',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Azul',
                'precio' => 6,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/camisetas/hombre_informal_camiseta_azul_001.png',
                'url' => 'https://daw05.medacarena.com.es/busqueda?controller=search&s=hombre_informal_camiseta_azul_001',
            ],
            [
                'nombre' => 'Camiseta',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Marron',
                'precio' => 7,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/camisetas/hombre_informal_camiseta_maron_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/101-hombreinformalcamisetamaron001.html',
            ],
            // Pantalones
            [
                'nombre' => 'Pantalon',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Amarillo',
                'precio' => 5,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/pantalon/hombre_informal_pantalon_amarillo_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/88-hombreinformalpantalonamarillo.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Beige',
                'precio' => 15,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/pantalon/hombre_informal_pantalon_beige_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/87-hombreinformalpantalonbeige.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Blanco',
                'precio' => 15,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/pantalon/hombre_informal_pantalon_blanco_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/86-hombreinformalpantalonblanco.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Gris',
                'precio' => 20,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/pantalon/hombre_informal_pantalon_gris_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/85-hombreinformalpantalongris.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Naranja',
                'precio' => 23,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/pantalon/hombre_informal_pantalon_naranja_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/84-hombreinformalpantalonnaranja.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Negro',
                'precio' => 25,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/pantalon/hombre_informal_pantalon_negro_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/83-hombreinformalpantalonnegro.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Rojo',
                'precio' => 18,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/pantalon/hombre_informal_pantalon_rojo_001.jpg',
                'url' => 'https://daw05.medacarena.com.es/inicio/102-hombreinformalpantalonrojo.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Rosa',
                'precio' => 19,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/pantalon/hombre_informal_pantalon_rosa_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/103-hombreinformalpantalonrosa.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Verde',
                'precio' => 17,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/pantalon/hombre_informal_pantalon_verde_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/104-hombreinformalpantalonverde.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Azul',
                'precio' => 16,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/pantalon/hombre_informal_pantalon_azul_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/105-hombreinformalpantalonazul.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Marron',
                'precio' => 20,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/pantalon/hombre_informal_pantalon_marron_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/106-hombreinformalpantalonmarron.html',
            ],
            // Sudaderas
            [
                'nombre' => 'Sudadera',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Larga',
                'color' => 'Azul',
                'precio' => 12,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/sudaderas/hombre_formal_sudadera_azul_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/82-hombreinformalsudaderaazul.html',
            ],
            [
                'nombre' => 'Sudadera',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Larga',
                'color' => 'Blanco',
                'precio' => 13,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/sudaderas/hombre_formal_sudadera_blanco_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/81-hombreinformalsudaderablanco.html',
            ],
            [
                'nombre' => 'Sudadera',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Larga',
                'color' => 'Gris',
                'precio' => 14,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/sudaderas/hombre_formal_sudadera_gris_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/80-hombreinformalsudaderagris.html',
            ],
            [
                'nombre' => 'Sudadera',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Larga',
                'color' => 'Marron',
                'precio' => 13,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/sudaderas/hombre_formal_sudadera_marron_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/79-hombreinformalsudaderamarron.html',
            ],
            [
                'nombre' => 'Sudadera',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Larga',
                'color' => 'Negro',
                'precio' => 13,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/sudaderas/hombre_formal_sudadera_negro_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/78-hombreinformalsudaderanegro.html',
            ],
            [
                'nombre' => 'Sudadera',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Larga',
                'color' => 'Rojo',
                'precio' => 13,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/sudaderas/hombre_formal_sudadera_rojo_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/77-hombreinformalsudaderarojo.html',
            ],
            [
                'nombre' => 'Sudadera',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Larga',
                'color' => 'Amarillo',
                'precio' => 15,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/sudaderas/hombre_formal_sudadera_amarillo_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/95-hombreinformalsudaderaamarillo001.html',
            ],
            [
                'nombre' => 'Sudadera',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Larga',
                'color' => 'Beige',
                'precio' => 14,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/sudaderas/hombre_formal_sudadera_beige_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/96-hombreinformalsudaderabeige001.html',
            ],
            [
                'nombre' => 'Sudadera',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Larga',
                'color' => 'Rosa',
                'precio' => 14,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/sudaderas/hombre_formal_sudadera_rosa_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/103-hombreinformalpantalonrosa.html',
            ],
            [
                'nombre' => 'Sudadera',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Larga',
                'color' => 'Verde',
                'precio' => 15,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/sudaderas/hombre_formal_sudadera_verde_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/108-hombreinformalsudaderaverde.html',
            ],
            [
                'nombre' => 'Sudadera',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Larga',
                'color' => 'Naranja',
                'precio' => 16,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/sudaderas/hombre_formal_sudadera_naranja_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/112-hombreinformalsudaderanaranja.html',
            ],
            // Zapatos
            [
                'nombre' => 'Zapatos',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Azul',
                'precio' => 15,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/zapatos/hombre_informal_zapato_azul_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/76-hombreinformalzapatoazul.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Beige',
                'precio' => 19,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/zapatos/hombre_informal_zapato_beige_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/75-hombreinformalzapatobeige.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Blanco',
                'precio' => 16,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/zapatos/hombre_informal_zapato_blanco_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/74-hombreinformalzapatoblanco.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Gris',
                'precio' => 15,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/zapatos/hombre_informal_zapato_gris_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/73-hombreinformalzapatogris.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Negro',
                'precio' => 16,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/zapatos/hombre_informal_zapato_negro_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/72-hombreinformalzapatonegro.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Rojo',
                'precio' => 17,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/zapatos/hombre_informal_zapato_rojo_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/71-hombreinformalzapatorojo.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Amarillo',
                'precio' => 18,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/zapatos/hombre_informal_zapato_amarillo_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/113-hombreinformalzapatoamarillo.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Marron',
                'precio' => 20,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/zapatos/hombre_informal_zapato_marron_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/115-hombreinformalzapatomarron.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Naranja',
                'precio' => 19,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/zapatos/hombre_informal_zapato_naranja_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/117-hombreinformalzapatonaranja.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Rosa',
                'precio' => 21,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/zapatos/hombre_informal_zapato_rosa_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/118-hombreinformalzapatorosa.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Hombre',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Verde',
                'precio' => 22,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/informal/zapatos/hombre_informal_zapato_verde_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/122-hombreinformalzapatoverde.html',
            ],
            // Camisas
            [
                'nombre' => 'Camisa',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Larga',
                'color' => 'Beige',
                'precio' => 15,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/camisas/hombre_formal_camisa_larga_beige_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/69-hombreformalcamisabeige.html',
            ],
            [
                'nombre' => 'Camisa',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Larga',
                'color' => 'Blanco',
                'precio' => 13,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/camisas/hombre_formal_camisa_larga_blanca_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/68-hombreformalcamisablanca.html',
            ],
            [
                'nombre' => 'Camisa',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Larga',
                'color' => 'Blanco',
                'precio' => 17,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/camisas/hombre_formal_camisa_larga_blanca_002.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/68-hombreformalcamisablanca.html',
            ],
            [
                'nombre' => 'Camisa',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Larga',
                'color' => 'Blanco',
                'precio' => 17,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/camisas/hombre_formal_camisa_larga_blanca_003.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/68-hombreformalcamisablanca.html',
            ],
            [
                'nombre' => 'Camisa',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Larga',
                'color' => 'Marron',
                'precio' => 17,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/camisas/hombre_formal_camisa_larga_marron_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/67-hombreformalcamisamarron.html',
            ],
            [
                'nombre' => 'Camisa',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Larga',
                'color' => 'Negra',
                'precio' => 18,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/camisas/hombre_formal_camisa_larga_negra_002.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/66-hombreformalcamisanegra.html',
            ],
            [
                'nombre' => 'Camisa',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Larga',
                'color' => 'Negro',
                'precio' => 18,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/camisas/hombre_formal_camisa_larga_negro_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/66-hombreformalcamisanegro.html',
            ],
            [
                'nombre' => 'Camisa',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Larga',
                'color' => 'Rojo',
                'precio' => 20,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/camisas/hombre_formal_camisa_larga_roja_003.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/65-hombreformalcamisaroja.html',
            ],
            [
                'nombre' => 'Camisa',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Larga',
                'color' => 'Amarillo',
                'precio' => 19,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/camisas/hombre_formal_camisa_larga_amarillo_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/124-hombreformalcamisalargaamarillo.html',
            ],
            [
                'nombre' => 'Camisa',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Larga',
                'color' => 'Rosa',
                'precio' => 18,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/camisas/hombre_formal_camisa_larga_rosa_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/126-hombreformalcamisalargarosa001.html',
            ],
            [
                'nombre' => 'Camisa',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Larga',
                'color' => 'Verde',
                'precio' => 17,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/camisas/hombre_formal_camisa_larga_verde_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/128-hombreformalcamisalargaverde.html',
            ],
            [
                'nombre' => 'Camisa',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Larga',
                'color' => 'Gris',
                'precio' => 16,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/camisas/hombre_formal_camisa_larga_gris_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/130-hombreformalcamisalargagris.html',
            ],
            [
                'nombre' => 'Camisa',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Larga',
                'color' => 'Naranja',
                'precio' => 20,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/camisas/hombre_formal_camisa_larga_naranja_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/132-hombreformalcamisalarganaranja.html',
            ],
            [
                'nombre' => 'Camisa',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Larga',
                'color' => 'Azul',
                'precio' => 22,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/camisas/hombre_formal_camisa_larga_azul_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/134-hombreformalcamisalargaazul.html',
            ],
            [
                'nombre' => 'Camisa',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Larga',
                'color' => 'Granate',
                'precio' => 22,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/camisas/hombre_formal_camisa_larga_granate_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/136-hombreformalcamisalargagranate.html',
            ],
            // Pantalones
            [
                'nombre' => 'Pantalon',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Amarillo',
                'precio' => 16,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/pantalon/hombre_formal_pantalon_amarillo_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/64-hombreformalpantalonamarillo.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Blanco',
                'precio' => 16,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/pantalon/hombre_formal_pantalon_blanco_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/63-hombreformalpantalonblanco.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Granate',
                'precio' => 14,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/pantalon/hombre_formal_pantalon_granate_001.png.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/62-hombreformalpantalongranate.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Gris',
                'precio' => 13,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/pantalon/hombre_formal_pantalon_gris_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/61-hombreformalpantalongris.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Negro',
                'precio' => 12,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/pantalon/hombre_formal_pantalon_negro_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/60-hombreformalpantalonnegro.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Rojo',
                'precio' => 12,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/pantalon/hombre_formal_pantalon_rojo_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/59-hombreformalpantalonrojo.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Verde',
                'precio' => 10,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/pantalon/hombre_formal_pantalon_verde_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/58-hombreformalpantalonverde.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Beige',
                'precio' => 14,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/pantalon/hombre_formal_pantalon_beige_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/139-hombreformalpantalonbeige.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Rosa',
                'precio' => 16,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/pantalon/hombre_formal_pantalon_rosa_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/141-hombreformalpantalonrosa.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Naranja',
                'precio' => 15,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/pantalon/hombre_formal_pantalon_naranja_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/143-hombreformalpantalonnaranja.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Azul',
                'precio' => 18,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/pantalon/hombre_formal_pantalon_azul_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/145-hombreformalpantalonazul.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Marrón',
                'precio' => 17,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/pantalon/hombre_formal_pantalon_marron_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/146-hombreformalpantalonmarron.html',
            ],
            // Zapatos
            [
                'nombre' => 'Zapatos',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Azul',
                'precio' => 40,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/zapatos/hombre_formal_zapato_azul_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/57-hombreformalzapatoazul.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Blanco',
                'precio' => 30,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/zapatos/hombre_formal_zapato_blanco_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/56-hombreformalzapatoblanco.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Blanco',
                'precio' => 36,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/zapatos/hombre_formal_zapato_blanco_002.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/56-hombreformalzapatoblanco.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Marron',
                'precio' => 30,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/zapatos/hombre_formal_zapato_marron_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/55-hombreformalzapatomarron.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Marron',
                'precio' => 30,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/zapatos/hombre_formal_zapato_marron_002.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/55-hombreformalzapatomarron.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Negro',
                'precio' => 32,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/zapatos/hombre_formal_zapato_negro_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/54-hombreformalzapatonegro.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Negro',
                'precio' => 32,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/zapatos/hombre_formal_zapato_negro_002.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/54-hombreformalzapatonegro.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Mujer',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Azul',
                'precio' => 32,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/formal/pantalones/mujer_formal_pantalon_azul_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/35-mujerformalpantalonazul.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Mujer',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Gris',
                'precio' => 16,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/formal/pantalones/mujer_formal_pantalon_gris_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/33-mujerformalpantalongris.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Mujer',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Negro',
                'precio' => 16,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/formal/pantalones/mujer_formal_pantalon_negro_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/32-mujerformalpantalonnegro.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Mujer',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Rojo',
                'precio' => 16,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/formal/pantalones/mujer_formal_pantalon_rojo_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/31-mujerformalpantalonrojo.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Mujer',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Rosa',
                'precio' => 17,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/formal/pantalones/mujer_formal_pantalon_rosa_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/30-mujerformalpantalonrosa.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Mujer',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Verde',
                'precio' => 17,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/formal/pantalones/mujer_formal_pantalon_verde_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/29-mujerformalpantalonverde.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Amarillo',
                'precio' => 40,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/zapatos/hombre_formal_zapato_amarillo_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/147-hombreformalzapatoamarillo.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Beige',
                'precio' => 30,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/zapatos/hombre_formal_zapato_beige_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/149-hombreformalzapatobeige.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Rojo',
                'precio' => 32,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/zapatos/hombre_formal_zapato_rojo_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/151-hombreformalzapatorojo.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Rosa',
                'precio' => 36,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/zapatos/hombre_formal_zapato_rosa_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/153-hombreformalzapatorosa.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Verde',
                'precio' => 30,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/zapatos/hombre_formal_zapato_verde_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/155-hombreformalzapatoverde.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Gris',
                'precio' => 32,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/zapatos/hombre_formal_zapato_gris_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/150-hombreformalzapatogris001.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Naranja',
                'precio' => 40,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/zapatos/hombre_formal_zapato_naranja_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/160-hombreformalzapatonaranja.html',
            ],
            // Vestidos
            [
                'nombre' => 'Vestido',
                'genero' => 'Mujer',
                'tipo' => 'Formal',
                'largo' => 'Larga',
                'color' => 'Amarillo',
                'precio' => 22,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/formal/vestidos/mujer_formal_vestido_amarillo_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/53-mujerformalvestidoamarillo.html',
            ],
            [
                'nombre' => 'Vestido',
                'genero' => 'Mujer',
                'tipo' => 'Formal',
                'largo' => 'Larga',
                'color' => 'Azul',
                'precio' => 21,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/formal/vestidos/mujer_formal_vestido_azul_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/52-mujerformalvestidoazul.html',
            ],
            [
                'nombre' => 'Vestido',
                'genero' => 'Mujer',
                'tipo' => 'Formal',
                'largo' => 'Larga',
                'color' => 'Gris',
                'precio' => 20,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/formal/vestidos/mujer_formal_vestido_gris_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/51-mujerformalvestidogris.html',
            ],
            [
                'nombre' => 'Vestido',
                'genero' => 'Mujer',
                'tipo' => 'Formal',
                'largo' => 'Larga',
                'color' => 'Negro',
                'precio' => 20,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/formal/vestidos/mujer_formal_vestido_negro_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/50-mujerformalvestidonegro.html',
            ],
            [
                'nombre' => 'Vestido',
                'genero' => 'Mujer',
                'tipo' => 'Formal',
                'largo' => 'Larga',
                'color' => 'Rosa',
                'precio' => 22,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/formal/vestidos/mujer_formal_vestido_rosa_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/49-mujerformalvestidorosa.html',
            ],
            [
                'nombre' => 'Vestido',
                'genero' => 'Mujer',
                'tipo' => 'Formal',
                'largo' => 'Larga',
                'color' => 'Verde',
                'precio' => 22,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/formal/vestidos/mujer_formal_vestido_verde_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/48-mujerformalvestidoverde.html',
            ],
            [
                'nombre' => 'Vestido',
                'genero' => 'Mujer',
                'tipo' => 'Formal',
                'largo' => 'Larga',
                'color' => 'Beige',
                'precio' => 22,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/formal/vestidos/mujer_formal_vestido_biege_001.png',
                'url' => 'https://m.media-amazon.com/images/I/314AsnOJzdL._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg',
            ],
            [
                'nombre' => 'Vestido',
                'genero' => 'Mujer',
                'tipo' => 'Formal',
                'largo' => 'Larga',
                'color' => 'Rojo',
                'precio' => 22,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/formal/vestidos/mujer_formal_vestido_rojo_001.png',
                'url' => 'https://m.media-amazon.com/images/I/314AsnOJzdL._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg',
            ],
            [
                'nombre' => 'Vestido',
                'genero' => 'Mujer',
                'tipo' => 'Formal',
                'largo' => 'Larga',
                'color' => 'blanco',
                'precio' => 22,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/formal/vestidos/mujer_formal_vestido_blanco_001.png',
                'url' => 'https://m.media-amazon.com/images/I/314AsnOJzdL._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg',
            ],
            [
                'nombre' => 'Vestido',
                'genero' => 'Mujer',
                'tipo' => 'Formal',
                'largo' => 'Larga',
                'color' => 'Naranja',
                'precio' => 22,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/formal/vestidos/mujer_formal_vestido_naranja_001.png',
                'url' => 'https://m.media-amazon.com/images/I/314AsnOJzdL._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg',
            ],
            [
                'nombre' => 'Vestido',
                'genero' => 'Mujer',
                'tipo' => 'Formal',
                'largo' => 'Larga',
                'color' => 'Marron',
                'precio' => 22,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/formal/vestidos/mujer_formal_vestido_marron_001.png',
                'url' => 'https://m.media-amazon.com/images/I/314AsnOJzdL._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg',
            ],

            // Zapatos
            [
                'nombre' => 'Zapatos',
                'genero' => 'Mujer',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Amarillo',
                'precio' => 20,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/formal/zapatos/mujer_formal_zapato_amarillo_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/47-mujerformalzapatoamarillo.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Mujer',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Azul',
                'precio' => 32,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/formal/zapatos/mujer_formal_zapato_azul_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/46-mujerformalzapatoazul.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Mujer',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Blanco',
                'precio' => 35,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/formal/zapatos/mujer_formal_zapato_blanco_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/45-mujerformalzapatoblanco.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Mujer',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Marron',
                'precio' => 35,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/formal/zapatos/mujer_formal_zapato_marron_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/44-mujerformalzapatomarron.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Mujer',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Negro',
                'precio' => 40,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/formal/zapatos/mujer_formal_zapato_negro_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/43-mujerformalzapatonegro.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Mujer',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Rosa',
                'precio' => 40,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/formal/zapatos/mujer_formal_zapato_rosa_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/42-mujerformalzapatorosa.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Mujer',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Beige',
                'precio' => 30,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/formal/zapatos/mujer_formal_zapato_beige_001.png',
                'url' => 'https://m.media-amazon.com/images/I/314AsnOJzdL._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Mujer',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Rojo',
                'precio' => 35,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/formal/zapatos/mujer_formal_zapato_rojo_001.png',
                'url' => 'https://m.media-amazon.com/images/I/314AsnOJzdL._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Mujer',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Verde',
                'precio' => 40,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/formal/zapatos/mujer_formal_zapato_verde_001.png',
                'url' => 'https://m.media-amazon.com/images/I/314AsnOJzdL._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Mujer',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Gris',
                'precio' => 30,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/formal/zapatos/mujer_formal_zapato_gris_001.png',
                'url' => 'https://m.media-amazon.com/images/I/314AsnOJzdL._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Mujer',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Naranja',
                'precio' => 32,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/formal/zapatos/mujer_formal_zapato_naranja_001.png',
                'url' => 'https://m.media-amazon.com/images/I/314AsnOJzdL._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg',
            ],
            // Camisetas
            [
                'nombre' => 'Camiseta',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Amarillo',
                'precio' => 5,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/camiseta/mujer_informal_camiseta_amarillo_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/41-mujerinformalcamisetaamarillo.html',
            ],
            [
                'nombre' => 'Camiseta',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Azul',
                'precio' => 5,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/camiseta/mujer_informal_camiseta_azul_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/40-mujerinformalcamisetaazul.html',
            ],
            [
                'nombre' => 'Camiseta',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Blanco',
                'precio' => 6,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/camiseta/mujer_informal_camiseta_blanco_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/39-mujerinformalcamisetablanco.html',
            ],
            [
                'nombre' => 'Camiseta',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Negro',
                'precio' => 6,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/camiseta/mujer_informal_camiseta_negro_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/38-mujerinformalcamisetanegro.html',
            ],
            [
                'nombre' => 'Camiseta',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Rojo',
                'precio' => 6,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/camiseta/mujer_informal_camiseta_rojo_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/37-mujerinformalcamisetarojo.html',
            ],
            [
                'nombre' => 'Camiseta',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Rosa',
                'precio' => 6,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/camiseta/mujer_informal_camiseta_rosa_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/36-mujerinformalcamisetarosa.html',
            ],
            [
                'nombre' => 'Camiseta',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Beige',
                'precio' => 7,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/camiseta/mujer_informal_camiseta_beige_001.png',
                'url' => 'https://m.media-amazon.com/images/I/314AsnOJzdL._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg',
            ],
            [
                'nombre' => 'Camiseta',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Verde',
                'precio' => 8,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/camiseta/mujer_informal_camiseta_verde_001.png',
                'url' => 'https://m.media-amazon.com/images/I/314AsnOJzdL._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg',
            ],
            [
                'nombre' => 'Camiseta',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Gris',
                'precio' => 7,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/camiseta/mujer_informal_camiseta_gris_001.png',
                'url' => 'https://m.media-amazon.com/images/I/314AsnOJzdL._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg',
            ],
            [
                'nombre' => 'Camiseta',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Naranja',
                'precio' => 7,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/camiseta/mujer_informal_camiseta_naranja_001.png',
                'url' => 'https://m.media-amazon.com/images/I/314AsnOJzdL._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg',
            ],
            [
                'nombre' => 'Camiseta',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Marron',
                'precio' => 6,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/camiseta/mujer_informal_camiseta_marron_001.png',
                'url' => 'https://m.media-amazon.com/images/I/314AsnOJzdL._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg',
            ],
            // Pantalones
            [
                'nombre' => 'Pantalon',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Azul',
                'precio' => 16,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/pantalones/mujer_informal_pantalon_azul_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/35-mujerinformalpantalonazul.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Gris',
                'precio' => 16,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/pantalones/mujer_informal_pantalon_gris_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/33-mujerinformalpantalongris.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Negro',
                'precio' => 16,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/pantalones/mujer_informal_pantalon_negro_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/32-mujerinformalpantalonnegro.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Rojo',
                'precio' => 16,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/pantalones/mujer_informal_pantalon_rojo_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/31-mujerinformalpantalonrojo.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Rosa',
                'precio' => 16,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/pantalones/mujer_informal_pantalon_rosa_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/30-mujerinformalpantalonrosa.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Verde',
                'precio' => 15,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/pantalones/mujer_informal_pantalon_verde_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/29-mujerinformalpantalonverde.html',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Amarillo',
                'precio' => 17,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/pantalones/mujer_informal_pantalon_amarillo_001.png',
                'url' => 'https://m.media-amazon.com/images/I/314AsnOJzdL._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Beige',
                'precio' => 18,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/pantalones/mujer_informal_pantalon_beige_001.png',
                'url' => 'https://m.media-amazon.com/images/I/314AsnOJzdL._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Blanco',
                'precio' => 19,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/pantalones/mujer_informal_pantalon_blanco_001.png',
                'url' => 'https://m.media-amazon.com/images/I/314AsnOJzdL._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Naranja',
                'precio' => 20,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/pantalones/mujer_informal_pantalon_naranja_001.png',
                'url' => 'https://m.media-amazon.com/images/I/314AsnOJzdL._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg',
            ],
            [
                'nombre' => 'Pantalon',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Marron',
                'precio' => 18,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/pantalones/mujer_informal_pantalon_marron_001.png',
                'url' => 'https://m.media-amazon.com/images/I/314AsnOJzdL._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg',
            ],
            // Zapatos
            [
                'nombre' => 'Zapatos',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Azul',
                'precio' => 15,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/zapatos/mujer_informal_zapato_azul_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/28-mujerinformalzapatoazul.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Beige',
                'precio' => 32,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/zapatos/mujer_informal_zapato_beige_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/27-mujerinformalzapatoamarillo.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Blanco',
                'precio' => 32,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/zapatos/mujer_informal_zapato_blanco_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/24-mujerinformalzapatoamarillo.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Marron',
                'precio' => 31,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/zapatos/mujer_informal_zapato_marron_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/22-mujerinformalzapatoamarillo.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Negro',
                'precio' => 31,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/zapatos/mujer_informal_zapato_negro_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/25-mujerinformalzapatoamarillo.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Rosa',
                'precio' => 10,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/zapatos/mujer_informal_zapato_rosa_001.png',
                'url' => 'https://daw05.medacarena.com.es/inicio/26-mujerinformalzapatoamarillo.html',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Amarillo',
                'precio' => 20,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/zapatos/mujer_informal_zapato_amarillo_001.png',
                'url' => 'https://m.media-amazon.com/images/I/314AsnOJzdL._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Rojo',
                'precio' => 22,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/zapatos/mujer_informal_zapato_roja_001.png',
                'url' => 'https://m.media-amazon.com/images/I/314AsnOJzdL._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Verde',
                'precio' => 24,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/zapatos/mujer_informal_zapato_verde_001.png',
                'url' => 'https://m.media-amazon.com/images/I/314AsnOJzdL._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Gris',
                'precio' => 26,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/zapatos/mujer_informal_zapato_gris_001.png',
                'url' => 'https://m.media-amazon.com/images/I/314AsnOJzdL._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Mujer',
                'tipo' => 'Informal',
                'largo' => 'Corta',
                'color' => 'Naranja',
                'precio' => 28,
                'img' => 'http://localhost/proyectoDaw/public/storage/mujer/informal/zapatos/mujer_informal_zapato_naranja_001.png',
                'url' => 'https://m.media-amazon.com/images/I/314AsnOJzdL._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg',
            ],
            [
                'nombre' => 'Zapatos',
                'genero' => 'Hombre',
                'tipo' => 'Formal',
                'largo' => 'Corta',
                'color' => 'Granate',
                'precio' => 28,
                'img' => 'http://localhost/proyectoDaw/public/storage/hombre/formal/zapatos/hombre_formal_zapato_granate_001.png',
                'url' => 'https://m.media-amazon.com/images/I/314AsnOJzdL._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg',
            ],
        ];

        foreach ($productos as $producto) {
            create_clothes_table::create($producto);
        }
    }
}
